version: '3.3'

services:
  postgres_ciencia:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ:America/La_Paz
    ports:
      - '5436:5432'
    volumes:
      - D:/Projects/Docker/postgres_init:/var/lib/postgresql/data